### ISSUE TITLE
Scoop mirroring outdated software

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/scoopinstaller.github.io#81]
Hey, I'd really appreciate someone could make my [scoop bucket](https://github.com/couleur-tweak-tips/utils/tree/main/bucket) was included in scoop.sh, and listed before these unmaintained copies of my bucket which have old versions of my software

outdated results: https://scoop.sh/#/apps?q=smoothie

my software's maintained manifest: https://github.com/couleur-tweak-tips/utils/blob/main/bucket/smoothie.json

**Comment by gpailler** [comment]
Hello,

Thank you for reporting this issue. Based on what I see on https://scoop.sh/#/apps?q=smoothie, your app is referenced by some meta buckets, which are displayed first because they appear more relevant based on popularity.

If you select "Distinct manifest only," you should be the only result, as your repo was the first to release a new version. However, it doesn't work in your specific case because you have updated the manifest without changing the version number. Consequently, the search engine displays the oldest bucket that has published the version version (okibcn/ScoopMaster in this case).

To resolve your issue, you can:
- Bump the version in your manifest. Then, you should be the only result when "Distinct manifest only" is selected.
- Open issues on these meta buckets and request to be dereferenced.

Thanks
